### ISSUE TITLE
Hey Dev!

### ISSUE THREAD

**Issue by CT-40** [HashPowerMonsterCoin/HashPowerMonster-Project#1]
Hey there!
I don’t mean this the wrong way, but is this a serious project or a “just for fun” project? 

Thanks!

**Comment by HashPowerMonsterCoin** [comment]
Hi :)

Stay connected with our git! We are going to specify more details about it!

**Comment by le2Ks** [comment]
> Hi :)
> 
> Stay connected with our git! We are going to specify more details about it!

Please remove the proxy from "node1.hashpower.monster" on CloudFlare. Otherwise it is impossible to connect.

**Comment by HashPowerMonsterCoin** [comment]
> > Hi :)
> > Stay connected with our git! We are going to specify more details about it!
> 
> Please remove the proxy from "node1.hashpower.monster" on CloudFlare. Otherwise it is impossible to connect.

Please open a new ticket issue, we already fixed it. Setup a node and remove from .config file in .hashpowermonster folder.

**Comment by le2Ks** [comment]
> > > Hi :)
> > > Stay connected with our git! We are going to specify more details about it!
> > 
> > 
> > Please remove the proxy from "node1.hashpower.monster" on CloudFlare. Otherwise it is impossible to connect.
> 
> Please open a new ticket issue, we already fixed it. Setup a node and remove from .config file in .hashpowermonster folder.

Hi, the issue still hasn’t been resolved. The "node1.hashpower.monster" address is still pointing to a proxied Cloudflare IP address, something like:

```
Name:    node1.hashpower.monster
Addresses:  2606:4700:130:436c:6f75:6466:6c61:7265
           172.64.80.1
```

This proxy mechanism prevents anyone from connecting directly to the official Hashpower Monster nodes.

To resolve this, you’ll just need to disable the proxy setting in Cloudflare and set it to “DNS ONLY.”

**Comment by le2Ks** [comment]
It works now
